### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by TylorS** [mostjs/dom-event#1]
# Overview

Publish this library to NPM
# Motivation

So we can all use it ;)

**Comment by briancavalier** [comment]
Thanks for the nudge :smile:  I was planning to write unit tests first.  Should be able to do that within the next couple of days.

**Comment by TylorS** [comment]
:+1: I didn't even look that far :smile: 
I can likely help with that as well, if you'd like

**Comment by briancavalier** [comment]
I started: https://travis-ci.org/mostjs/dom-event

That might be enough to publish a version.

**Comment by TylorS** [comment]
The tests seem to cover the essentials. I like the `FakeEventTarget()`. I wish we were able to use that for our tests :smile: 

Anything you think isn't covered (enough)?

**Comment by briancavalier** [comment]
> I like the FakeEventTarget()

Feel free to duplicate it :)  It's pretty short.

> Anything you think isn't covered (enough)?

Ideally, there would be tests for each of the convenience functions (e.g. `click`) that verifies that it actually results in calling `addEventListener` with the correct event name and capture.  That can probably be done with metaprogramming (i.e. a loop) rather than cutting/pasting.

**Comment by TylorS** [comment]
> Feel free to duplicate it :) It's pretty short

I don't think we _could_ duplicate it, we have to test things like event bubbling etc.

> tests for each of the convenience functions

I can do that :)

**Comment by briancavalier** [comment]
> I can do that :)

Much appreciated!

**Comment by TylorS** [comment]
Check #2

**Comment by briancavalier** [comment]
[`npm install @most/dom-event`](https://www.npmjs.com/package/@most/dom-event) is a thing :rocket:
