### ISSUE TITLE
@most/dom-event@1.2.0 requires a peer of most@^0.19.0 but none was installed.

### ISSUE THREAD

**Issue by joshburgess** [mostjs/dom-event#17]
Hi, I keep getting this warning along with an unmet peer depedency warning for most@1.0.0 in my project, despite having the most recent releases of both installed.

I'm not sure what the problem is exactly, but I'm guessing the most@^0.19.0 is only good for up to the highest version of the same major version?

Should we update the @^version for most here or is there another way to get rid of this warning?

**Comment by briancavalier** [comment]
Hey @joshburgess. Thanks! Everything should still work as long you're using npm 3. We do need to publish a new version to update the peer dep. I hope to get to that soon.

**Comment by briancavalier** [comment]
@joshburgess `@most/dom-event` 1.2.1 has a peerDep for `most` 1.0.0.  Could you try 1.2.1?  Thanks!

**Comment by briancavalier** [comment]
Also, [1.3.0 is out now](https://github.com/mostjs/dom-event/releases) :)

**Comment by joshburgess** [comment]
Updated to the most recent of both and the warning is gone. Thanks! :)

**Comment by briancavalier** [comment]
Cool!  Thanks for following up.
